# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 学而时习之
subtitle: 程序猿,攻城狮,爱生活,爱编程。
description: 知行合一 ｜ 编程 ｜ 记录 ｜ 随笔 ｜ Perl ｜ 前端 ｜ HTML ｜ CSS ｜ JavaScript
author: 慕容羽兮
avatar: /images/avatar.jpg
email: niuleipeng@gmail.com
language: zh-Hans
timezone: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://niuleipeng.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:


# Archives #存档，这里的说明好像不对。全部选择1，这个选项与主题中的选项有时候会有冲突
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1


# Server #本地服务参数
# ## Hexo uses Connect as a server
# ## You can customize the logger format as defined in
# ## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: true
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: hexo-theme-next

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
    type: git
    repository: git@github.com:saturnast/saturnast.github.com.git
    branch: 
    message: 

markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]


#=============================================================================
# NexT Theme configuration
# =============================================================================

# 多说帐号
# duoshuo_shortname: lniu

# DISQUS 帐号 （如果已经设置 多说 帐号，此选项将被跳过）
# disqus_shortname: your-disqus-shortname


# 社交链接，将在侧栏中显示
social:
    GitHub: https://github.com/saturnast
    Twitter: https://twitter.com/saturnast
    微博: http://weibo.com/spiritast
    豆瓣: http://www.douban.com/people/iFallenAngel/
    知乎: http://www.zhihu.com/people/mu-rong-yu-xi
# 等等

# Creative Commons 4.0 International License.
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: by-nc-sa


# Google 站长工具验证，请选择 `HTML Meta` 验证方式
# See: https://www.google.com/webmasters/
google_site_verification: VvyjvVXcJQa0QklHipu6pwm2PJGnnchIqX7s5JbbT_0

# Google 分析 ID
google_analytics: UA-64460330-1


# 百度统计 ID，此 ID 是百度统计提供脚本中 hm.js? 后面那串字符，非百度统计帐号
baidu_analytics:

# 站点起始时间
since: 2015

# =============================================================================
# End NexT Theme configuration
# =============================================================================
